### ISSUE TITLE
where is BasicMessageHandler and BasicIndexHandler？

### ISSUE THREAD

**Issue by xushan** [BigDataDevs/kafka-elasticsearch-consumer#27]
in the impl.examples directory , there does not have class BasicMessageHandler  and BasicIndexHandler, i can used RawLogMessageHandlerImpl or SimpleMessageHandlerImpl instead BasicMessageHandler ,but how about the BasicIndexHandler?

**Comment by xushan** [comment]
in proj kafka-elasticsearch-standalone-consumer, i can find the BasicIndexHandler, such as 
package org.elasticsearch.kafka.consumer;

import java.util.HashMap;

/**
 * Basic Index handler that returns ElasticSearch index name defined 
 * in the configuration file as is
 * 
 * @author marinapopova
 *
 */
public class BasicIndexHandler implements IndexHandler {

	private final ConsumerConfig config;
	private String indexName;
	private String indexType;
	
	public BasicIndexHandler(ConsumerConfig config) {
		this.config = config;
		indexName = config.esIndex;
		if (indexName == null || indexName.trim().length() < 1)
			indexName = DEFAULT_INDEX_NAME;
		indexType = config.esIndexType;
		if (indexType == null || indexType.trim().length() < 1)
			indexType =  DEFAULT_INDEX_TYPE;

	}

	@Override
	public String getIndexName(HashMap<String, Object> indexLookupProperties) {
		return indexName;
	}

	@Override
	public String getIndexType(HashMap<String, Object> indexLookupProperties) {
		return indexType;
	}

}


maybe i should create one like that.

**Comment by mpopova-yottaa** [comment]
Hi, Xushan,
We have refactored the project a bit but did not update all documentation at the same time :)
We've just updated it now - please take a look. There is no BasicMessageHandler anymore, as well as IIndexHandler interface, it is much simpler now.

Let us know if you have further questions,
Marina

**Comment by xushan** [comment]
Hi, mpopova-yottaa 
thank you for your reply, I known you are one of the three developers for proj kafka-elasticsearch-consumer on github，thanks for your contribution for this proj，I also learning and using it，but there some questions about the proj，hope you can give me some answers，thankfulness.
    Q1:why using kafka low consumer API？ Just for getting kafka partition and offset info？and why not using high level API？
    Q2:as known to all, one consumer can playload mssages from all the partition of one topic，and why this proj still has division  for partition？just for distributed deploy?
    Q3:one instance of the proj can only playload one topic of a kafka cluster， will there support mulit-topic in the future？
    Q4: Elasticsearch has update to version 2.1+，this proj can support ES 2.1 or not？

best wishes to you!

**Comment by ppine7** [comment]
hi, Xushan,
thanks for using the project!

Answers to your questions:
1:why using kafka low consumer API？ Just for getting kafka partition and offset info？and why not using high level API？
Answer: yes, we are using low-level consumers to explicitly manage offsets. It is especially important for disaster recovery. We spent a lot of time hardening the code to handle all kinds of failures and insure no messages are lost - or at least they are stored into failed_events log for possible re-processing.  

Having said that, we are actively working on moving to kafka 0.9 - where low-level and high-level consumers are merged. This will allow us to simplify the code a lot, get rid of all re-ballancing/leader-detection logic, but still have direct control over offset management.

Q2:as known to all, one consumer can playload mssages from all the partition of one topic，and why this proj still has division for partition？just for distributed deploy?
Answer: yes, this is done for greater scalability and independent offset management of each partition. As I specified above, we are striving to be very fault-tolerant and not loose any messages. It is much more reliable to implement this by handling each partition in a separate thread/job

Q3:one instance of the proj can only playload one topic of a kafka cluster， will there support mulit-topic in the future？
Answer: we have not planned for this yet - but can consider. You can easily start separate instances of the indexer for different topics though - to achieve what you need.

Q4: Elasticsearch has update to version 2.1+，this proj can support ES 2.1 or not？
Answer: not yet, it only supports ES <= 1.6. But we are actively working on upgrade to ES 2.3 - should be available in a few weeks.

thanks,
Marina

**Comment by xushan** [comment]
HI,Marina
I am very glad to see  your detailed reply, and I have known more about this project，if there has any more question，I'll consult with you again，thanks a lot.
