### ISSUE TITLE
indexer.properties is NOT changed which is specified when running 

### ISSUE THREAD

**Issue by StevenXiaoZhao** [BigDataDevs/kafka-elasticsearch-consumer#37]
Sorry, I am not familiar with Spring. When I run following command, my indexer.properties is NOT changed at all

> ./kafka-elasticsearch-consumer -Dindexer.properties=/your/absolute/path/kafka-es-indexer.properties -Dlogback.configurationFile=/your/absolute/path/logback.xml_

So I try to add JAVA_OPTS instead, which works.

**Comment by mpopova-yottaa** [comment]
Hi, I'm not sure what you mean that the "indexer.properties is NOT changed at all" ?
In any case - glad that it works with JAVA_OPTS for you

**Comment by dhyaneshm** [comment]
hi @StevenXiaoZhao  . If you are using the shell script to kick-off the job yes you can just use JAVA_OPTS to set env variables(It uses/follows the Gradle application plugin standard -- Docs https://docs.gradle.org/current/userguide/application_plugin.html) . 

I think we have to fix our documentation . -D will work if you want to run from Eclipse or if you are trying to run if from gradlew run command

Thanks for using our product and adding feedback

**Comment by StevenXiaoZhao** [comment]
@dhyaneshm @mpopova-yottaa thanks for your explanation. I used it in docker, so setting JAVA_OPTS  works for me. Meanwhile, I hope there would be an official docker on docker hub.

**Comment by dhyaneshm** [comment]
@StevenXiaoZhao . We do have a docker-hub location for the project https://hub.docker.com/r/bigdatadevs/kafka-elasticsearch-consumer/ . We're currently not pushing the latest changes to dockerhub as part of CI build . We'll make that change soon . 

FYI .I'll also close this issue .
