### ISSUE TITLE
Multiple Topics

### ISSUE THREAD

**Issue by StevenXiaoZhao** [BigDataDevs/kafka-elasticsearch-consumer#38]
Hi,
What is the best practice of supporting multiple topics? It seems the config file just supports single topic.
Thank you

**Comment by ppine7** [comment]
hi, @StevenXiaoZhao ! 
Thanks for using the project!
The current version allows you to run one instance of indexer for one topic only.
WE are working on the upgrade to Kafka0.9 - which will support multiple topics natively (should happen soon, in a few weeks).
In the meantime - you can run multiple instances of indexer - one per topic.

thanks,
Marina

**Comment by StevenXiaoZhao** [comment]
Thanks for your replay
