### ISSUE TITLE
OOM when running kafka-elasticsearch-standalone-consumer

### ISSUE THREAD

**Issue by zousheng** [BigDataDevs/kafka-elasticsearch-consumer#40]
Hi team,

I used the old version kafka-elasticsearch-standalone-consumer to consumer kafka and store data in es, but that version always oom after running a short period of time, I am wondering if this is solved in this new project?

Thanks

**Comment by ppine7** [comment]
Hi, @zousheng,
Which version of the old indexer are you using? branch2.0 should not have any OOM issues - back when we were using it we were running it for weeks on end and no OOM issues. Of course, depends on how large your messages could be and the batch sizes you configured in your indexer properties, but in general - it is very stable.

The new one, in this repo, also should not have any such issues. We are running it for weeks without restarts, monitoring JVM , and do not see any increase on the memory usage over time at all. 
We do use -Xmx7g - but we are planning to trim it down as we barely use 2g out of that heap 99% of the time, over multiple weeks running.

**Comment by zousheng** [comment]
Thanks, I will try this version and monitor it for few days

**Comment by zousheng** [comment]
Hi @ppine7, I tried the old version app with 16G memory machine, and it almost eats up the memory,  here is the pid resource usage, so far I didn't see the mem usage goes down, just wonder if there is essential issue in the code especially when dealing with large amount of data? thanks


  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 3175 xxx   20   0 22.8g  11g  15m S 316.9 73.0  67:08.64 /usr/java/jdk1.8.0_20/bin/java -Xmx8g

**Comment by zousheng** [comment]
Here is the oom log:
ang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "elasticsearch[Doctor Spectrum][generic][T#11]" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "elasticsearch[Malice][generic][T#9]" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "kafka-indexer-consumer-thread-187" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "elasticsearch[Victor Mancha][generic][T#9]" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "elasticsearch[Crime Master][generic][T#16]" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "elasticsearch[Ego the Living Planet][generic][T#10]"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "elasticsearch[Ego the Living Planet][generic][T#10]"
Exception in thread "elasticsearch[Mad Thinker][generic][T#13]" java.lang.OutOfMemoryError: GC overhead limit exceeded


Maybe I6G memory is not enough?

**Comment by ppine7** [comment]
Hi, @zousheng ,
What specific old version did you use? From the master branch or from the branch2.0 ?
Also, do you have your own message handlers added?
16G is a huge heap - it is more than enough for most cases - so the issue must be in the code.
In any case - we do not support the old versions anymore, sorry... too much has changed in the new one, which is very stable, and does not have OOM issues.

thanks,
Marina
