### ISSUE TITLE
kafkaClientService.close blocked

### ISSUE THREAD

**Issue by chengxiayan** [BigDataDevs/kafka-elasticsearch-consumer#42]
Hi , when the docker lost connections to the kafka cluster, kafkaClientServce.close() will be called.  And curator.close() will block closing, which prevents reInitKafka() retrying. Can I remove the code connecting to zookeeper ? I haven't found any reference to the zookeeper client.

**Comment by ppine7** [comment]
Hi, @chengxiayan ,
You are correct - the curator is not needed anymore, it is a remainder form the old version....
I have removed it , with all corresponding now-unnecessary properties.
The latest build (1.0.121) has the fix.

thanks,
Marina
