### ISSUE TITLE
NoClassDef Exception Error creating bean with name 'kafkaClientService': Invocation of init metho d failed

### ISSUE THREAD

**Issue by Mohandm** [BigDataDevs/kafka-elasticsearch-consumer#43]
Hi ,
I followed the steps provided and when i run the application i get runtime exception.
Below is the log statements

Exception in thread "main" org.springframework.beans.factory.BeanCreationExcepti
on: Error creating bean with name 'kafkaClientService': Invocation of init metho
d failed
Error creating bean with name 'kafkaClientService': Invocation of init metho
d failed; nested exception is java.lang.NoClassDefFoundError: org/apache/zookeep
er/Watcher
16:42:53.835 [main] ERROR o.e.k.i.service.JobManagerService - ERROR: Failure cre
ating a consumer job, exiting:
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBea
nPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProc
essor.java:136)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanF
actory.java:408)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.initializeBean(AbstractAutowireCapableBeanFactory.java:1564)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:204)
org.springframework.beans.factory.BeanCreationException: Error creating bean wit
h name 'kafkaClientService': Invocation of init method failed; nested exception
is java.lang.NoClassDefFoundError: org/apache/zookeeper/Watcher
        at org.springframework.context.support.AbstractApplicationContext.getBea
n(AbstractApplicationContext.java:981)
        at org.elasticsearch.kafka.indexer.service.JobManagerService.processAllT
hreads(JobManagerService.java:68)
        at org.elasticsearch.kafka.indexer.KafkaESIndexerProcess.main(KafkaESInd
exerProcess.java:17)
Caused by: java.lang.NoClassDefFoundError: org/apache/zookeeper/Watcher
        at com.netflix.curator.framework.CuratorFrameworkFactory$Builder.build(C
uratorFrameworkFactory.java:103)
        at com.netflix.curator.framework.CuratorFrameworkFactory.newClient(Curat
orFrameworkFactory.java:73)
        at org.elasticsearch.kafka.indexer.service.KafkaClientService.connectToZ
ooKeeper(KafkaClientService.java:151)
        at org.elasticsearch.kafka.indexer.service.KafkaClientService.init(Kafka
ClientService.java:111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBea
nPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProc
essor.java:136) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanF
actory.java:408) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.initializeBean(AbstractAutowireCapableBeanFactory.java:1564) ~[spring-be
ans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans
-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBea
nPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.ja
va:349)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4
.1.9.RELEASE.jar:4.1.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:322) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]

        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBea
nPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPost
Processor.java:300)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:204) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.getBea
n(AbstractApplicationContext.java:981) ~[spring-context-4.1.9.RELEASE.jar:4.1.9.
RELEASE]
        at org.elasticsearch.kafka.indexer.service.JobManagerService.processAllT
hreads(JobManagerService.java:68) ~[main/:na]
        at org.elasticsearch.kafka.indexer.KafkaESIndexerProcess.main(KafkaESInd
exerProcess.java:17) [main/:na]
Caused by:      at org.springframework.beans.factory.annotation.InitDestroyAnnot
ationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBean
PostProcessor.java:133)
java.lang.NoClassDefFoundError: org/apache/zookeeper/Watcher
        at com.netflix.curator.framework.CuratorFrameworkFactory$Builder.build(C
uratorFrameworkFactory.java:103) ~[curator-framework-1.0.1.jar:na]
        at com.netflix.curator.framework.CuratorFrameworkFactory.newClient(Curat
orFrameworkFactory.java:73) ~[curator-framework-1.0.1.jar:na]
        at org.elasticsearch.kafka.indexer.service.KafkaClientService.connectToZ
ooKeeper(KafkaClientService.java:151) ~[main/:na]
        at org.elasticsearch.kafka.indexer.service.KafkaClientService.init(Kafka
ClientService.java:111) ~[main/:na]
        ... 9 more
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.
0_92]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62) ~[na:1.8.0_92]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43) ~[na:1.8.0_92]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBea
nPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.ja
va:349) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBea
nPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPost
Processor.java:300) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBea
nPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProc
essor.java:133) ~[spring-beans-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.Watcher
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0
_92]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_92]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.
8.0_92]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_92]
        ... 20 common frames omitted
16:42:53.840 [Thread-0] INFO  o.s.c.s.ClassPathXmlApplicationContext - Closing o
rg.springframework.context.support.ClassPathXmlApplicationContext@c39f790: start
up date [Tue Jul 19 16:42:47 IST 2016]; root of context hierarchy
16:42:53.841 [Thread-0] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning c
ached instance of singleton bean 'lifecycleProcessor'
16:42:53.841 [Thread-0] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Destroying
singletons in org.springframework.beans.factory.support.DefaultListableBeanFacto
ry@544a2ea6: defining beans [objectMapper,kafkaClientService,elasticSearchClient
Service,messageHandler,elasticSearchBatchService,jobManagerService,org.springfra
mework.context.annotation.internalConfigurationAnnotationProcessor,org.springfra
mework.context.annotation.internalAutowiredAnnotationProcessor,org.springframewo
rk.context.annotation.internalRequiredAnnotationProcessor,org.springframework.co
ntext.annotation.internalCommonAnnotationProcessor,org.springframework.beans.fac
tory.config.PropertyPlaceholderConfigurer#0,org.springframework.context.annotati
on.ConfigurationClassPostProcessor.importAwareProcessor,org.springframework.cont
ext.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor];
root of factory hierarchy
16:42:53.841 [Thread-0] DEBUG o.s.c.a.CommonAnnotationBeanPostProcessor - Invoki
ng destroy method on bean 'jobManagerService': public void org.elasticsearch.kaf
ka.indexer.service.JobManagerService.stop()
16:42:53.841 [Thread-0] INFO  o.e.k.i.service.JobManagerService - About to stop
all consumer jobs ...
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.Watcher
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 20 more
16:43:03.843 [Thread-0] INFO  o.e.k.i.service.JobManagerService - executorServic
e threads stopped
16:43:03.843 [Thread-0] INFO  o.e.k.i.service.JobManagerService - Stop() finishe
d
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_92\bin\java.exe'' finished wi
th non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 20.808 secs

**Comment by ppine7** [comment]
Hi, @Mohandm ,
First, how do you run the app? via gradle run or via script?
Second, what version of Kafka are you running?

thanks
Marina

**Comment by Mohandm** [comment]
I ran it via grade.
0.10.0.0 is the Kafka version

**Comment by ppine7** [comment]
At this time we do not yet support Kafka 0.10, we are on the 0.8 version. We are working on the 0.9-0.10 upgrade but it will be a few weeks before it is ready.
