### ISSUE TITLE
Does not compile against ES 2.3.3

### ISSUE THREAD

**Issue by ashokc** [BigDataDevs/kafka-elasticsearch-consumer#45]
Guess the api has changed since this package was developed... Getting errors like:

IndexerJob.java:[8,40] error: cannot find symbol
[ERROR] package org.elasticsearch.common.settings

IndexerJob.java:[86,14] error: constructor TransportClient in class TransportClient cannot be applied to given types;
[ERROR] actual argument Settings cannot be converted to Injector by method invocation conversion

etc...

What is the highest version of elasticsearch that is supported... ?

Thanks

**Comment by ppine7** [comment]
Hi, @ashokc ,
The ES version used is 2.3.3 on the 'master' branch - so it should definitely work. Take a look at the build.gradle:
    compile group: 'org.elasticsearch', name: 'elasticsearch', version: '2.3.3'

Are you getting this error from your application that uses the indexer as a dependency? or just running the indexer as is?

Marina

**Comment by ashokc** [comment]
Hi Marina,

My error. Somehow I grabbed a branch2.0 version with a pom and everything.

Compiled fine with gradle & es 2.3.3 using the master version

Thank you very much

Ashok

**Comment by ashokc** [comment]
Hi Marina,

The script 'run_index.sh' needed to be corrected.

from

$JAVA_HOME/bin/java -Xmx1g -cp $CLASS_PATH -Dlogback.configurationFile=$LOGBACK_CONFIG_FILE org.elasticsearch.kafka.indexer.KafkaElasticSearchProcess $INDEXER_PROPERTIES_FILE

to

$JAVA_HOME/bin/java -Xmx1g -cp $CLASS_PATH -Dlogback.configurationFile=$LOGBACK_CONFIG_FILE -**Dindexer.properties=$INDEXER_PROPERTIES_FILE** org.elasticsearch.kafka.indexer.**KafkaESIndexerProcess**

With that in place we can now run it as

./run_index.sh

**Comment by ppine7** [comment]
Awesome, thanks, Ashok! - I will fix it!
Good catch - I was mostly running the app via 'gradle run' and did not test the script lately.

Marina

**Comment by ppine7** [comment]
The run_indexer.sh script and documentation are updated
