### ISSUE TITLE
Daily indices etc...

### ISSUE THREAD

**Issue by ashokc** [BigDataDevs/kafka-elasticsearch-consumer#46]
This is not an issue - just a question. Is there an easy way to get this to generate daily indices etc... much like logstash does...

without having to modify the code here:

service/ElasticSearchBatchService.java:    public void **addEventToBulkRequest**(String inputMessage, String **indexName**, String indexType, String eventUUID, String routingValue) throws ExecutionException {

Thanks

**Comment by ppine7** [comment]
Yes, the easiest way to accomplish this - is to add logic to determine index name (and type) in your custom MessageHandler.  By default, you use the SimpleMessageHandlerImpl implementation of the IMessageHandler interface, and it has this implementation for the addMessageToBatch() method:

```
	@Override
	public void addMessageToBatch(byte[] inputMessage, Long offset) throws Exception {
		String eventUUID = null; // we don't need a UUID for this simple scenario
		String routingValue = null; // we don't need routing for this simple scenario		
		elasticSearchBatchService.addEventToBulkRequest(
			new String(inputMessage), indexName, indexType, eventUUID, routingValue);
	}

```
All you need to do is either modify this class, or , better, create your own MyMessageHandlerImpl class that will have a custom logic to determine index name, something like this:

```
	@Override
	public void addMessageToBatch(byte[] inputMessage, Long offset) throws Exception {
		String eventUUID = null; // we don't need a UUID for this simple scenario
		String routingValue = null; // we don't need routing for this simple scenario		
                /// pseudo code:
                /// String date_day_value = /// get a string representation of current's date and day - as you wish to format it
                 String myIndexName = date_day_value + some_index_name_suffix;
		elasticSearchBatchService.addEventToBulkRequest(
			new String(inputMessage), myIndexName, indexType, eventUUID, routingValue);
	}

```
Then you just have to modify the kafka-es-context-public.xml (or your own Spring app config if applicable) and set your own implementation of the messageHandler bean:
```

<bean id="messageHandler"
          class="org.blah.blah.MyMessageHandlerImpl"
          scope="prototype"/>

```

Marina
