### ISSUE TITLE
Please support for ES 5.x

### ISSUE THREAD

**Issue by whitetiger21022014** [BigDataDevs/kafka-elasticsearch-consumer#58]
Hello,
It works with Elastic-search  2.x so well but can not work ES 5.x
Thanks,

**Comment by mpopova-yottaa** [comment]
Thank you for using the project - we are very glad it works well for you! :)
We are definitely going to add support for ES5.x and Kafka 0.10.x - but it will take a few weeks to get there.
Stay tuned!

**Comment by mohigup** [comment]
Hi
I am waiting for support for ES 5.x as well

**Comment by mpopova-yottaa** [comment]
it's coming .... just slowly :)

**Comment by ppine7** [comment]
ES5.x is now supported!
