### ISSUE TITLE
my confusions about "determin offset for partitions" 

### ISSUE THREAD

**Issue by chengxiayan** [BigDataDevs/kafka-elasticsearch-consumer#78]
in the function ConsumerManager.determinOffsetForAllPartitionsAndSeek, line 156 is to poll from kafka, which I think may poll some messages that will never be consumed. And the "commitSync"  instruction at end of the function will commit offset after polling, leading to messages polled are skipped. While the partition's start option is "RESTART", it will start from position after polling. My English is poor, thanks for reading this.

**Comment by mpopova-yottaa** [comment]
Hi, chengxiayan,
You are right - you found a bug! 
It is indeed possible to loose the messages of the first poll() if you are using the RESTART option....
We will fix this very soon,

Thank you for finding and reporting the issue!

**Comment by dhyaneshm** [comment]
Hey thanks . I think this is the bug we were chasing for some time . Please look at : https://stackoverflow.com/questions/41177614/kafka-0-9-java-consumer-skipping-offsets-during-application-restart 
We'll try to get a FIX soon .

**Comment by ppine7** [comment]
We just fixed this issue - please try the latest build! 
Thanks again for troubleshooting and finding the root cause of the issue
